app:
  port: 3000
  pub_dir: "/public"
  max_resources_num: 1
  submission_msg_char_limit: 500
  cookie_secret: "your secret key salt goes here"
aws:
  accountID: AmazonAccountId
  accessKeyId: AmazonAWSAccessKeyId
  secretKey: AmazonAWSSecretAccessKey
  bucket: AmazonS3Bucket
  S3region: US_EAST_1
  SQSregion: US_EAST_1
  SQSQueueName: potluck_stage
