app:
  port: 3000
  name: "NPR Potluck"
  pub_dir: "/public"
  max_resources_num: 1
  submission_msg_char_limit: 700
  cookie_secret: "your secret key salt goes here"
aws:
  accountID: AmazonAccountId
  accessKeyId: AmazonAWSAccessKeyId
  secretKey: AmazonAWSSecretAccessKey
  bucket: AmazonS3Bucket
  cacheTTL: 86400
  cdnDomain: "potluckstage.s3.amazonaws.com"
  S3region: US_EAST_1
  SQSregion: US_EAST_1
  SQSQueueName: potluck_stage
mysql:
  host: "your.db.host.com"
  user: root
  pass: password
  database: databaseName
